# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\x12\nml_service\"1\n\x06Search\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x12\n\nimage_path\x18\x02 \x01(\t\"A\n\nPrediction\x12\x33\n\x0f\x66\x61shion_product\x18\x01 \x03(\x0b\x32\x1a.ml_service.FashionProduct\"\xac\x02\n\x0e\x46\x61shionProduct\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0f\n\x07s3_path\x18\x03 \x01(\t\x12\x17\n\x0fmaster_category\x18\x04 \x01(\t\x12\x14\n\x0csub_category\x18\x05 \x01(\t\x12\x14\n\x0c\x61rticle_type\x18\x06 \x01(\t\x12\x13\n\x0b\x62\x61se_colour\x18\x07 \x01(\t\x12\x0e\n\x06season\x18\x08 \x01(\t\x12\x0c\n\x04year\x18\t \x01(\t\x12\r\n\x05usage\x18\n \x01(\t\x12\x0e\n\x06gender\x18\x0b \x01(\t\x12\x1c\n\x14product_display_name\x18\x0c \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\r \x01(\t\x12\x12\n\ncreated_at\x18\x0e \x01(\t\x12\x11\n\tembedding\x18\x0f \x03(\x02\x32\x42\n\tMLService\x12\x35\n\x07Predict\x12\x12.ml_service.Search\x1a\x16.ml_service.Predictionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCH']._serialized_start=32
  _globals['_SEARCH']._serialized_end=81
  _globals['_PREDICTION']._serialized_start=83
  _globals['_PREDICTION']._serialized_end=148
  _globals['_FASHIONPRODUCT']._serialized_start=151
  _globals['_FASHIONPRODUCT']._serialized_end=451
  _globals['_MLSERVICE']._serialized_start=453
  _globals['_MLSERVICE']._serialized_end=519
# @@protoc_insertion_point(module_scope)
